import { TunnelServer, AppRule, AdvancedSettings } from './types';

export const SERVERS: TunnelServer[] = [
  {
    id: 'sg-1',
    name: 'Singapore Premium-01',
    country: 'Singapore',
    flag: '🇸🇬',
    ip: '128.199.100.42',
    load: 42,
    ping: 28,
    ports: [22, 443, 80, 1080],
  },
  {
    id: 'sg-2',
    name: 'Singapore Game-Optimized',
    country: 'Singapore',
    flag: '🇸🇬',
    ip: '139.59.250.111',
    load: 78,
    ping: 32,
    ports: [22, 443, 80, 3128],
  },
  {
    id: 'us-west',
    name: 'US West - Silicon Valley',
    country: 'United States',
    flag: '🇺🇸',
    ip: '104.248.60.10',
    load: 18,
    ping: 154,
    ports: [22, 443, 80, 8080],
  },
  {
    id: 'us-east',
    name: 'US East - New York',
    country: 'United States',
    flag: '🇺🇸',
    ip: '142.93.55.201',
    load: 35,
    ping: 188,
    ports: [22, 443, 80, 1080],
  },
  {
    id: 'eu-west',
    name: 'EU Central - Frankfurt',
    country: 'Germany',
    flag: '🇩🇪',
    ip: '46.101.200.75',
    load: 29,
    ping: 110,
    ports: [22, 443, 80, 8080],
  },
  {
    id: 'eu-ams',
    name: 'EU West - Amsterdam',
    country: 'Netherlands',
    flag: '🇳🇱',
    ip: '188.166.12.98',
    load: 55,
    ping: 124,
    ports: [22, 443, 80, 1080],
  },
  {
    id: 'ap-tokyo',
    name: 'JP Northeast - Tokyo',
    country: 'Japan',
    flag: '🇯🇵',
    ip: '172.105.200.14',
    load: 61,
    ping: 85,
    ports: [22, 443, 80, 1080],
  },
  {
    id: 'ap-mumbai',
    name: 'IN West - Mumbai',
    country: 'India',
    flag: '🇮🇳',
    ip: '139.59.80.203',
    load: 48,
    ping: 45,
    ports: [22, 443, 80, 3128],
  },
];

export const INITIAL_APP_RULES: AppRule[] = [
  { id: 'app-1', name: 'Web Browser', packageName: 'com.android.chrome', icon: 'Globe', route: true },
  { id: 'app-2', name: 'Discord', packageName: 'com.discord', icon: 'MessageSquare', route: true },
  { id: 'app-3', name: 'Git & Command Line', packageName: 'system.terminal', icon: 'Terminal', route: false },
  { id: 'app-4', name: 'YouTube & Media', packageName: 'com.google.android.youtube', icon: 'Play', route: true },
  { id: 'app-5', name: 'Online Gaming Portals', packageName: 'com.riotgames.valorant', icon: 'Gamepad2', route: false },
];

export const DEFAULT_SETTINGS: AdvancedSettings = {
  dnsType: 'cloudflare',
  customDnsPrimary: '1.1.1.1',
  customDnsSecondary: '1.0.0.1',
  localPort: 1080,
  mtu: 1500,
  enableUdp: true,
  reconnectAttempts: 5,
  slowDnsKey: 'opentunnel-pub-key-7x89c02v1b',
  slowDnsNs: 'ns.opentunnel.sh',
  sshConnectFrom: 'http_proxy',
  sshCustomPayload: false,
  enableAesNi: true,
  enableKernelRouting: false,
};
